name: hsactor

extra-source-files:
- ../protobuf/**/*.proto

# custom-setup:
#   dependencies:
#     - base
#     - Cabal
#     - proto-lens-protoc

tests:
  spec:
    main: Spec.hs
    ghc-options:
      - -fprint-potential-instances
    source-dirs:
      - test
    dependencies:
      - hspec
      - hsactor
      - hspec-wai
      - hspec-wai-json
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

# library:
#   ghc-options: 
#     - -O2
#   dependencies:
#     - http-media
#   source-dirs:
#     - protobuf
#   exposed-modules: 
#     - Proto.Cam.Messages

library:
  ghc-options: 
    - -O2
  dependencies:
    - http-media
    - base64-bytestring
    - aeson
    - bytestring
    - containers
    - data-default-class
    - lens-family
    - proto-lens
    - word8
    - text
  source-dirs:
    - src
    - protobuf
  exposed-modules: 
    - Proto.Cam.Messages
    - Item
    - Schedule
    - Protobuf
    - CRUD
    
executables:  
  hsactor:
    ghc-options: 
      - -Wall
      - -O2
      - -threaded 
      - -rtsopts
      - -with-rtsopts=-N30 
      - -fprint-potential-instances
    main: exe/Main.hs
    dependencies:
      - hsactor

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - aeson
  - wai
  - stm
  - warp
  - text
  - bytestring
  - microlens
  - proto-lens
  - proto-lens-protoc
  - lens-labels
