name: hsactor

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - hsactor
      - hspec-wai
      - hspec-wai-json
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

library:
  ghc-options: 
  - -O2
  source-dirs:
    - src

executables:  
  hsactor:
    ghc-options: 
    - -Wall
    - -O2
    - -threaded 
    - -rtsopts
    - -with-rtsopts=-N30 
    main: exe/Main.hs
    dependencies:
      - hsactor

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - aeson
  - wai
  - warp
  - text
  - bytestring
