version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    networks:
      - kafka
    expose:
      - "2181"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
      ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL: ERROR
      ZOOKEEPER_LOG4J_LOGGERS: 'org.apache.zookeeper.server=ERROR,kafka=ERROR,kafka.authorizer.logger=ERROR,state.change.logger=ERROR,kafka.request.logger=ERROR,kafka.controller=ERROR,kafka.producer.async.DefaultEventHandler=ERROR,kafka.log.LogCleaner=ERROR,kafka.network.RequestChannel$$=ERROR'

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    networks:
      - kafka
    expose:
      - "9092"
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_LOG4J_LOGGERS: 'kafka=ERROR,kafka.authorizer.logger=ERROR,state.change.logger=ERROR,kafka.request.logger=ERROR,kafka.controller=ERROR,kafka.producer.async.DefaultEventHandler=ERROR,kafka.log.LogCleaner=ERROR,kafka.network.RequestChannel$$=ERROR'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 20000
    links:
      - zookeeper

networks:
  kafka:
    driver: bridge
